name: collection_ext
description: Extension functions to Dart collections.
version: 0.0.1
author: xinthink <yingxinwu.g@gmail.com>
homepage: xinthink.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

dev_dependencies:
  test:
  pedantic: ^1.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
